// <auto-generated />
namespace DuraboStockManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTypeMouvementOnMouvementClasss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTypeMouvementOnMouvementClasss));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281137041_AddTypeMouvementOnMouvementClasss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
